# -*- coding: utf-8 -*-
"""fengshui.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rBHc3VNlW2XavGt7pansJypXLucz2ZOB
"""

import cv2
import torch
from ultralytics import YOLO

def analyze_image(image_path):
    # Load pre-trained YOLOv8 model
    model = YOLO("yolov8n.pt")  # This automatically downloads if not available

    # Read the image
    image = cv2.imread(image_path)

    # Run object detection
    results = model(image)

    # Get detected objects
    detected_objects = []
    for result in results:
        for obj in result.boxes.data:
            x1, y1, x2, y2, conf, cls = obj.cpu().numpy()
            class_name = model.names[int(cls)]
            detected_objects.append((class_name, (x1, y1, x2, y2)))

    return detected_objects, image # Return the image along with detected objects


def vastu_suggestions(detected_objects):
    vastu_rules = {
        "bed": "Beds should be placed in the southwest direction for stability.",
        "sofa": "Sofas should be placed against the south or west wall.",
        "mirror": "Avoid mirrors facing the bed; they should be on the north or east wall.",
        "stove": "The kitchen stove should be in the southeast corner.",
        "desk": "Study tables should be in the north or east direction for better focus."
    }

    suggestions = []
    for obj, _ in detected_objects:
        if obj in vastu_rules:
            suggestions.append(f"{obj.capitalize()}: {vastu_rules[obj]}")

    return suggestions

# Example usage
image_path = "bedroom.jpg"  # Provide your image path
detected_objects, image = analyze_image(image_path) # Get the image
suggestions = vastu_suggestions(detected_objects)

print("Detected Objects:", detected_objects)
print("Vastu Suggestions:")
# image # Assuming you want to display the image, uncomment this line if you have the appropriate display setup.
# In Jupyter Notebook, you might use:
# from IPython.display import display
# display(image)
display(image)
for suggestion in suggestions:
    print("-", suggestion)